cmcasset/objects/CMC_Asset__c.object
<CustomObject>
    <description>Asset in the CMC Cloud Asset Library</description>
    <fields>
        <fullName>Asset_Platform__c</fullName>
        <description>The primary platform the asset is built on.</description>
        <inlineHelpText>The primary platform the asset is built on.</inlineHelpText>
        <label>Asset Platform</label>
        <picklist>
            <picklistValues>
                <fullName>Android</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apple OSX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cast Iron</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google App Engine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heroku</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Linux/UNIX/BSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Microsoft Windows</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MySQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VmForce</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Asset_Type__c</fullName>
        <description>Coarse asset categorization.</description>
        <inlineHelpText>Coarse asset categorization.</inlineHelpText>
        <label>Asset Type</label>
        <picklist>
            <picklistValues>
                <fullName>Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Framework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Implementation Utility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sample</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Uses__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of other stories for which this asset has been used to help implement.</description>
        <inlineHelpText>Number of other stories for which this asset has been used to help implement.</inlineHelpText>
        <label>Number of Reuses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Preview_Media_Type__c</fullName>
        <description>Format of the media (screenshot, video tutorial) to be used to preview the asset.</description>
        <inlineHelpText>Format of the media (screenshot, video tutorial) to be used to preview the asset.</inlineHelpText>
        <label>Preview Media Type</label>
        <picklist>
            <picklistValues>
                <fullName>jpg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>png</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>swf</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preview_Media_URL__c</fullName>
        <description>URL of the screenshot or video allowing others to preview the asset.</description>
        <inlineHelpText>URL of the screenshot or video allowing others to preview the asset.</inlineHelpText>
        <label>Preview Media URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Release_Stage__c</fullName>
        <description>Asset release process</description>
        <inlineHelpText>Stages in the process of releasing an Asset.  All Assets will enter as Candidates, and be reviewed by the CAL team.  Only Active Assets will be posted to Chatter, and be available in Asset search.</inlineHelpText>
        <label>Release Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Candidate</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Short Description of the Asset. Visible in search results and list views.</description>
        <inlineHelpText>Short Description of the Asset. Visible in search results and list views.</inlineHelpText>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cmcasset/classes/CMC_AssetLibraryController.cls
// 
// (c) 2009 Appirio, Inc.
//
// Generate a new lead from a sales-related case
//
// ??    Will/Ray      Original
// 3/6/2012     Fisher	 Added callout to track search terms
//

public with sharing class CMC_AssetLibraryController {

public string Tags{ get; set; }
	public string terms{ get; set; }
	public String param;
	public boolean renderListView {get; set; }
	public Integer recordCount {get;set;}
	//list of reusable assets to display
	public List< CMC_Asset__c > ReusableAssets {get;set;}
	//current sort direction. defaults to asc
	public String SortDir 
	{
		get  { if (this.SortDir == null) {  this.SortDir = 'ASC'; } return this.SortDir;  }
		set;
	}
	//current field to sort by. defaults to name
	public String SortField 
	{
		get  { if (this.SortField == null) {this.SortField = 'Name'; } return this.SortField;  }
		set;
	}

	public String Debug { get; set; }

	public CMC_AssetLibraryController()
	{
		this.ReusableAssets = new List< CMC_Asset__c >(); 
		this.Debug = '';
		this.Terms = '';
		this.param = '';
		renderListView = false;
		recordCount = 0;
		//go get all available public tags
		string tags = '[';
		for (CMC_Asset__Tag tag : [SELECT Name FROM CMC_Asset__Tag WHERE Type = 'Public' ORDER by Name ASC limit 1000]) {  
			tags += '{ name:"' + tag.Name + '"},';
		}
		tags += ']';
		this.Tags = tags;
	}
//execute search for the text entered
	public PageReference Search() 
	{
		renderListView = false;
		String searchTerms = '';
		param = String.escapeSingleQuotes(Apexpages.currentPage().getParameters().get('terms'));
		system.debug ('param = ' + param);
		List<String> terms = param.split(',');
		for (String term : terms){
			term = term.trim();
			if (term.length() > 0)
			{
				if (searchTerms.length() > 0){
					searchTerms += ' AND ';
				}
				searchTerms +=  term ;  
			}
		}
		system.debug('indexof * = ' + searchTerms.indexOf('*'));
		Boolean executeSearch;
		executeSearch = true;
		Integer searchPos = searchTerms.indexOf('*');
		Integer termLength;
		termLength = searchTerms.Length();
		system.debug('TermLength=' + termLength);
		system.debug('searchpos = ' + searchPos);
		if (searchPos <> -1) {
			if (termLength < 3) {
				executeSearch = false;
			}
		}
		else {
			// means we have an *
			if (termLength < 3) {
			   executeSearch = false;
			}
		}
		system.debug('executeSearch =' + executeSearch);
		if (executeSearch){
			this.Terms = searchTerms;
			
			this.Terms = searchTerms += ' OR "' + removeCommainSearchTerms(param) + '"';
			system.debug('terms = ' + this.Terms);
			SoslSearch();
			// callout to REST call to track search
			// could move this to a @future call in the future
			String query = '/AssetLibrary/?searchterms=' + param + '&recordsReturned=' + recordCount ;
			CMC_SearchTermsCallout callout = new CMC_SearchTermsCallout();
			callout.SendSearchTermsToAWS(query);
		}
		else
		{
			ApexPages.Message searchMsg = new ApexPages.Message(ApexPages.Severity.FATAL,'The minimum number of characters is 3 e.g. cmc or cm*');
			ApexPages.addMessage(searchMsg);
			recordCount = 0;
			ReusableAssets.clear();
		}
		return null;
}
	//search across assets and tags
	private void SoslSearch(){
		String.escapeSingleQuotes(this.Terms);
		system.debug('Terms = ' + this.Terms);
		String searchTerms = this.Terms;
		if (searchTerms.length() > 0)
		{
			String searchquery='FIND \'' + searchTerms + '\' IN ALL FIELDS RETURNING CMC_Asset__c(id,name, Short_Description__c,  Asset_Platform__c, Number_of_Uses__c,  Preview_Media_URL__c, Preview_Media_Type__c, Asset_Type__c WHERE Release_Stage__c = \'Active\' ORDER BY ' + this.SortField + ' ' + this.SortDir +') LIMIT 50'; 
			this.Debug = searchquery;
			this.ReusableAssets = new List< CMC_Asset__c >();
			List<List<SObject>> results =search.query(searchquery);
			if (results.size() > 0){
				Set<Id> itemIds = new Set<Id>();
				CMC_Asset__c asset;
				for(SObject sobj : results[0]){
					if (!itemIds.contains(sobj.id)){
						itemIds.add(sobj.id);
						asset = (CMC_Asset__c)sobj;
						this.ReusableAssets.add(asset);
					}
				}
				recordCount = ReusableAssets.size();
			}
			else 
				recordCount = 0;
				system.debug('reusable size = ' +ReusableAssets.size());    
		}
	}
	// handle the action of the commandlink
	public PageReference processListview() {
		renderListView = true;
		return null;
	}
	// handle the action of the commandlink
	public PageReference processSearchview() {
		renderListView = false;
		return null;
	}
	// toggles the sorting of query from asc<-->desc
	public void ToggleSort() 
	{
		this.SortDir = this.SortDir.equals('ASC') ? 'DESC' : 'ASC';
		this.SoslSearch();
	}
	
	private String removeCommainSearchTerms(String terms) {
		
		system.debug('parsing term = ' + terms);
		Pattern commapattern = Pattern.compile(',');
		String retString = commapattern.matcher(terms).replaceAll(' ');
		return retString;
	}
}